### ISSUE TITLE
Could you create a "development" branch (or another similar?)

### ISSUE THREAD

**Issue by sineverba** [itskenny0/Yeelight-PHP#2]
Hi!
I'm planning to extend your class. In detail,
+ move to Composer and to packagist, so it can be find
+ add discover section
+ reorganize a bit the code
+ add scrutinizer

and more on.

If you want, I will push sometime edit to a branch. But, ofc, I don't want use "master" but antoer one. Can you create a development branch?

I'm also using your library to my own project with telegram bot.

Have a nice day!

**Comment by itskenny0** [comment]
Hey there!

Sorry, but the main point of this class is to remain as simple as possible and I'm somewhat happy with the current state of it. 

It is licensed under The Unlicense, so I invite you to use the code any way you like. I would suggest you fork the repo and work on the fork instead; leaving the repo in my control doesn't make too much sense since I am likely not going to contribute that much.

Thanks a lot for your interest though!

Best,
kenny
